[package]
name = "dithereens"
version = "0.1.1"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2024"
keywords = ["graphics", "dithering", "images"]
categories = ["graphics", "multimedia::images"]
license = "Apache-2.0 OR BSD-3-Clause OR MIT OR Zlib"
description = "Functions & traits for quantizing values with error-diffusion"
exclude = [".github/**/*", "crates/**/*", "examples/**/*"]
readme = "README.md"
documentation = "https://docs.rs/dithereens/"
repository = "https://github.com/virtualritz/dithereens/"

[dependencies]
num-traits = "0.2"
rand = "0.9"
